name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Language Plugin:
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: percentage
          # plugin_languages_categories: yes
          plugin_languages_limit: 8
          # plugin_languages_analysis_timeout_repositories: 0
          repositories_skipped: nirokay/nirokay.github.io, nirokay/nirokay.com

          # Token:
          token: ${{ secrets.METRICS_TOKEN }}
